project:
  type: website

website:
  title: "Pranav's Quant Blog"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/pranavmittal611/
      - icon: github
        href: https://github.com/mlpranav
      - icon: twitter
        href: https://twitter.com/pranavmittal611

format:
  html:
    theme: darkly
    css: styles.css

resources:
  - CNAME

execute:
  freeze: true